### ISSUE TITLE
Interactive Feature nav item

### ISSUE THREAD

**Issue by liviatronic** [hard-g/acd#10]
Two small things:<br>

1. 'Interactive Feature' should either NOT be a link (as in production site) or clicking it could go to interactive feature
2. List item should NOT be numbered<br>

Production site:<br>
<img width="330" alt="Screen Shot 2022-09-25 at 11 22 23 AM" src="https://user-images.githubusercontent.com/33435482/192151486-fc26d203-3392-4d61-9ede-f5c58efceee1.png">
<br> Test site:<br>
<img width="348" alt="Screen Shot 2022-09-25 at 11 25 36 AM" src="https://user-images.githubusercontent.com/33435482/192151500-1ba817ea-20d6-4970-8e27-1f0d14e86c3b.png">

**Comment by boonebgorges** [comment]
Thanks for the screenshots. I've ported the production CSS responsible for this.
