### ISSUE TITLE
Multi-page document numbering

### ISSUE THREAD

**Issue by liviatronic** [hard-g/acd#12]
On test site, numbers for multi-page documents are above and to the left of the image, while on production site, numbers are centered below image.<br>
Test site:<br>
<img width="610" alt="Screen Shot 2022-09-25 at 11 32 20 AM" src="https://user-images.githubusercontent.com/33435482/192151870-f53a288c-5999-4426-818d-2ec4dde3dd31.png">
<br>
Production site:<br>
<img width="616" alt="Screen Shot 2022-09-25 at 11 32 27 AM" src="https://user-images.githubusercontent.com/33435482/192151885-98a9a5d5-04a8-48fa-80ac-ef0385147d96.png">

**Comment by boonebgorges** [comment]
Sorry about this - I had to rewrite some markup in order to fix some security and performance issues in this part of the code, and there was an incorrect closing tag that threw off the styling. It is now fixed.
