### ISSUE TITLE
Essay heading styling

### ISSUE THREAD

**Issue by liviatronic** [hard-g/acd#13]
Small style discrepancy: `lower-essay-header` is smaller font size on test site
<br>
https://hardg.com/acd/essay/memory-projects/
<br>
<img width="848" alt="Screen Shot 2022-09-25 at 11 35 57 AM" src="https://user-images.githubusercontent.com/33435482/192152040-a216e465-1f5b-4230-982e-88879519f3ed.png"><br>
<br>http://acampusdivided.umn.edu/index.php/essay/memory-projects/<br>
<img width="865" alt="Screen Shot 2022-09-25 at 11 36 02 AM" src="https://user-images.githubusercontent.com/33435482/192152054-5abee5bd-7d25-49d3-bba1-33fe301ac806.png">

**Comment by boonebgorges** [comment]
This was due to a load-order difference between the original build process and the one that I've jury-rigged together. I've worked around it.
