### ISSUE TITLE
'About' formatting issues

### ISSUE THREAD

**Issue by liviatronic** [hard-g/acd#14]
Looks like we lost some formatting on the 'About' page:<br>
https://hardg.com/acd/about/<br>
<img width="794" alt="Screen Shot 2022-09-25 at 11 39 44 AM" src="https://user-images.githubusercontent.com/33435482/192152181-ab01b58f-98ec-4fab-aa58-d4db43d875b0.png">
<br><br>
http://acampusdivided.umn.edu/index.php/about/<br>
<img width="829" alt="Screen Shot 2022-09-25 at 11 39 52 AM" src="https://user-images.githubusercontent.com/33435482/192152202-9bab7b9d-8cfa-46ee-b1bd-a3f9dcab420b.png">

**Comment by boonebgorges** [comment]
Sorry for missing this page in my review. I've now cleaned it up.
