### ISSUE TITLE
Styling issue: Margin-bottom for document paragraphs

### ISSUE THREAD

**Issue by liviatronic** [hard-g/acd#15]
Looks like we lost `margin-bottom` in the document descriptions. Arbitrary example here: https://acampusdivided.umn.edu/person/richard-m-scammon/<br>
Test site:<br>
<img width="715" alt="Screen Shot 2022-09-28 at 7 12 41 PM" src="https://user-images.githubusercontent.com/33435482/192904562-4c6234e6-7a6b-4d49-bf6f-9cc649a4cd82.png">
<br>
Production site:<br>
<img width="736" alt="Screen Shot 2022-09-28 at 7 12 49 PM" src="https://user-images.githubusercontent.com/33435482/192904580-6afc8b7a-93dc-426a-8e08-9c12ac267cd3.png">

**Comment by boonebgorges** [comment]
Thanks for the screenshots. This is now fixed: https://hardg.com/acd/person/richard-m-scammon/
