### ISSUE TITLE
Styling: 'X' alignment on filter buttons

### ISSUE THREAD

**Issue by liviatronic** [hard-g/acd#16]
Slight misalignment on filter buttons 'X': <br>
Test:<br>
<img width="142" alt="Screen Shot 2022-09-28 at 7 15 45 PM" src="https://user-images.githubusercontent.com/33435482/192904866-aa240690-ec2d-4a69-9a26-c4ad723d47ab.png">

<br>Production:<br>
<img width="134" alt="Screen Shot 2022-09-28 at 7 15 51 PM" src="https://user-images.githubusercontent.com/33435482/192904875-cdb4050b-8958-4512-bb6e-8581a0a88c5a.png">

**Comment by boonebgorges** [comment]
Fixed: https://hardg.com/acd/documents/?subject=african-american-students
