### ISSUE TITLE
Block quote font style and size

### ISSUE THREAD

**Issue by liviatronic** [hard-g/acd#17]
On test site, block quote styling is slightly different:

- Uses "false italics" ('SelfModern' with a slant applied by the browser) rather than pulling the italic font ('SelfModern-Italic')
- 21px instead of 19px

Test site:
<img width="712" alt="Screenshot 2022-11-10 at 1 47 50 PM" src="https://user-images.githubusercontent.com/33435482/201181312-681f7dbd-daa9-4eac-89a4-8be861778c32.png">

Production site:
<img width="813" alt="Screenshot 2022-11-10 at 1 47 37 PM" src="https://user-images.githubusercontent.com/33435482/201181430-e25d41ed-254f-4ce7-b9f0-9dd04dc06d72.png">

**Comment by boonebgorges** [comment]
These should now be fixed. See eg https://hardg.com/acd/essay/student-activism-in-context-of-1930s/
