### ISSUE TITLE
Quote attribution alignment

### ISSUE THREAD

**Issue by liviatronic** [hard-g/acd#18]
This was never addressed on the original build of the site, hoping we can do a few small alignment tweaks with the quote attributions! I know this is quite detailed, lmk if it's too fussy.

<img width="822" alt="Screenshot 2022-11-10 at 1 58 14 PM" src="https://user-images.githubusercontent.com/33435482/201183755-007e28e5-3227-4af4-b44a-32595afd9706.png">

1. Multiple lines would left align with the first line, leaving the em dash "hanging"
2. Right indent would align with the narrower paragraph above

**Comment by boonebgorges** [comment]
We can do that :)
![Screenshot_2022-11-10_16-06-58](https://user-images.githubusercontent.com/246627/201215784-3ee1496e-9d42-45f7-9f05-ff94b11c015a.png)

https://hardg.com/acd/essay/student-activism-in-context-of-1930s/

**Comment by liviatronic** [comment]
Looks perfect, thank you :)
