### ISSUE TITLE
Footnote link styling

### ISSUE THREAD

**Issue by liviatronic** [hard-g/acd#19]
Font size gets larger when it is turned into a link, ideally it would remain the same size as the rest of the footnote text.
<img width="717" alt="Screenshot 2022-11-10 at 2 08 19 PM" src="https://user-images.githubusercontent.com/33435482/201185002-d362fdfa-3add-4b70-891f-9e1a4d8c0e15.png">

**Comment by boonebgorges** [comment]
Good catch.  This should be fixed by 278c85e9bd
