### ISSUE TITLE
Lightbox <p>, wrong styling 

### ISSUE THREAD

**Issue by liviatronic** [hard-g/acd#2]
https://hardg.com/acd/
`<p>` styling has shifted, leading to cut off descriptions
Test site: <br>
<img width="375" alt="Screen Shot 2022-09-16 at 5 56 34 PM" src="https://user-images.githubusercontent.com/33435482/190807418-4df3c165-1951-4dd8-a6d7-4f16d18a0d61.png">
<br>Production site:<br>
<img width="375" alt="Screen Shot 2022-09-16 at 5 56 41 PM" src="https://user-images.githubusercontent.com/33435482/190807482-44b90964-8082-4e95-ab6b-ae02c1964102.png">

**Comment by boonebgorges** [comment]
Thanks, and sorry for the confusion. I've dug up the necessary styles from the production site and ported them over. When retesting, please be sure to do a hard-refresh or browser cache purge.
