### ISSUE TITLE
Quote block 'Add citation' prompt

### ISSUE THREAD

**Issue by liviatronic** [hard-g/acd#22]
This is a low priority, but wondering if it's possible to eliminate the 'Add citation' prompt that pops up when you add a quote block? My understanding is that we're not using this citation style at all, is that correct?

<img width="872" alt="Screenshot 2022-11-29 at 12 38 42 PM" src="https://user-images.githubusercontent.com/33435482/204607048-6171d155-51e7-473f-a862-c6a65ff1ee7d.png">

**Comment by boonebgorges** [comment]
Correct. I'd considered simply using the 'Add citation' feature of the Quote block, but it wasn't flexible enough to (easily) accommodate the specific styling conventions you were already using for attributions.

There's not an easy way to turn this feature off totally in WP so I've just hidden it with CSS. Feel free to give it a test on https://hardg.com/acd/ if you'd like.

**Comment by liviatronic** [comment]
Perfect, very helpful
