### ISSUE TITLE
errors on essay pages

### ISSUE THREAD

**Issue by liviatronic** [hard-g/acd#3]
https://hardg.com/acd/essay/student-movements-on-campus/
All essay pages have errors at the top <br>
<img width="1440" alt="Screen Shot 2022-09-16 at 5 59 37 PM" src="https://user-images.githubusercontent.com/33435482/190808526-0d5300fd-b6d3-448e-ab05-acd7b2530b5b.png">

**Comment by boonebgorges** [comment]
The theme was full of code that triggered PHP notices. They don't (and won't) show on the production site, and I'd mistakenly enabled their display on the test site for testing purposes. I've changed the config so they shouldn't show. I've also been fixing these notices in the codebase as I've found them.
