### ISSUE TITLE
Nav bar loss of functionality

### ISSUE THREAD

**Issue by liviatronic** [hard-g/acd#4]
The word 'essay' in the top nav bar should link to https://acampusdivided.umn.edu/index.php/essays/, on test site it is not a link<br>
<img width="411" alt="Screen Shot 2022-09-16 at 6 01 05 PM" src="https://user-images.githubusercontent.com/33435482/190809217-6bf23c36-ad34-474d-bbdb-fcb22cab9440.png">

**Comment by boonebgorges** [comment]
This is one of the changes that must have been implemented in a version of the site later than the one that Jared had provided to me. I've ported it from the production files.
