### ISSUE TITLE
Lightbox when accessed from essay, z-index order issue

### ISSUE THREAD

**Issue by liviatronic** [hard-g/acd#5]
https://hardg.com/acd/index.php/essay/political-surveillance-of-university/
When accessing the lightbox from an essay page, the overlay is sitting behind the nav bar, which makes it difficult to see the 'x' to close out and return to the essay. <br>
<img width="1438" alt="Screen Shot 2022-09-16 at 6 02 37 PM" src="https://user-images.githubusercontent.com/33435482/190810398-cdda6789-b86c-4c56-946b-2a4ba560c92d.png">

**Comment by boonebgorges** [comment]
I've made some changes that should address this.
