### ISSUE TITLE
Interactive feature doesn't appear to be working

### ISSUE THREAD

**Issue by liviatronic** [hard-g/acd#6]
https://hardg.com/acd/index.php/how-leaders-of-the-university-of-minnesota-used-and-abused-power/
This link goes to the homepage, not the interactive feature

**Comment by boonebgorges** [comment]
This is due to some URL format changes, which is related to the `index.php` issue that you laid out in your original document. I've fully fixed the config on the test site and I will follow the same procedure when we roll out to the production site.
