### ISSUE TITLE
Homepage links missing interactive feature

### ISSUE THREAD

**Issue by liviatronic** [hard-g/acd#7]
Block linking to interactive features is missing from homepage. <br>
Test site:<br>
<img width="1440" alt="Screen Shot 2022-09-16 at 6 06 51 PM" src="https://user-images.githubusercontent.com/33435482/190811800-70bd2645-ce92-4c13-89ee-d8144777221a.png">
Production site:<br>
<img width="1440" alt="Screen Shot 2022-09-16 at 6 06 38 PM" src="https://user-images.githubusercontent.com/33435482/190811869-d7b298be-ea71-4186-ad74-481f698b46c3.png">

**Comment by boonebgorges** [comment]
This is another change that was on the production site but not in the source files. I've ported it over.
