### ISSUE TITLE
Document zoom not working

### ISSUE THREAD

**Issue by liviatronic** [hard-g/acd#8]
https://hardg.com/acd/still_image/and-the-wolf-chewed-up-all-the-children/
When accessing a document from the 'documents' section, there are two issues:<br>

1. Clicking the image opens a new tab with the image url, making the user leave the site https://hardg.com/acd/wp-content/uploads/2017/09/1.2-And-the-Wolf-Chewed.jpg
2. Zoom functionality is totally broken, zoom in and out buttons don't work, 'x' doesn't close the image

**Comment by boonebgorges** [comment]
A JavaScript error was causing both of these issues. I've made some modifications that should fix the issues.
