### ISSUE TITLE
URL for 'Essays' nav link not working

### ISSUE THREAD

**Issue by liviatronic** [hard-g/acd#9]
This may be just a test site issue, but wanted to flag that 'Essays' links to 'https://hardg.com/acdhttps:/hardg.com/acd/essays' <br>
<img width="402" alt="Screen Shot 2022-09-25 at 11 17 24 AM" src="https://user-images.githubusercontent.com/33435482/192151210-ed93feb4-713f-447a-8bbe-cb329869239f.png">

**Comment by boonebgorges** [comment]
This was a typo in my work on #4 and should now be fixed.
